# Generated by Django 6.0.1 on 2026-02-03 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('issue', 'Выдача'), ('return', 'Возврат'), ('move', 'Перемещение'), ('repair', 'Ремонт'), ('write_off', 'Списание')], max_length=32)),
                ('condition', models.CharField(blank=True, choices=[('ok', 'Исправно'), ('need_repair', 'Требует ремонта'), ('damaged', 'Повреждено')], max_length=32)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='equipment.equipment')),
                ('location_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_from', to='equipment.location')),
                ('location_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_to', to='equipment.location')),
            ],
        ),
    ]
